# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

[[main]]
  name = "Biography"
  url = "#about"
  weight = 20
  
[[main]]
  name = "Experience"
  url = "#experience"
  weight = 30    

[[main]]
  name = "Publications"
  url = "#publications"
  weight = 40   

[[main]]
  name = "Talks"
  url = "#talks"
  weight = 50  

[[main]]
  name = "Projects"
  url = "#projects"
  weight = 60  

[[main]]
  name = "Awards & Grants"
  url = "#awardsgrants"
  weight = 70  

[[main]]
  name = "Training"
  url = "#training"
  weight = 80 

[[main]]
  name = "Skills"
  url = "#skills"
  weight = 90  

[[main]]
  name = "Posts"
  url = "#posts"
  weight = 100    

[[main]]
  name = "Blog"
  url = "#blog"
  weight = 110
  
[[main]]
  name = "Contact"
  url = "#contact"
  weight = 120
  
# [[main]]
  # name = "Highlighted Works"
  # url = "#featured"
  # weight = 90  


# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/files/cv.pdf` and uncomment the lines below.
# [[main]]
#    name = "CV"
#    url = "files/cv.pdf"
#    weight = 70
